# Generated by Django 4.0.5 on 2022-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0003_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
