# Generated by Django 4.0.5 on 2022-07-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0008_rides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rides',
            new_name='Ride',
        ),
    ]
