# Generated by Django 4.0.5 on 2022-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0009_rename_rides_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_date',
            field=models.DateField(null=True),
        ),
    ]
