# Generated by Django 4.0.5 on 2022-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
