# Generated by Django 4.0.5 on 2022-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0015_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(height_field=250, null=True, upload_to='avatars', width_field=250),
        ),
    ]
