# Generated by Django 4.0.5 on 2022-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_networking', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_image',
            field=models.ImageField(null=True, upload_to='ride_images'),
        ),
    ]
